# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# RUN: llc %s -mtriple=riscv64 -run-pass=riscv-copy-combine -verify-machineinstrs \
# RUN:   -o - | FileCheck %s -check-prefixes=COPY-COMBINE-INST

#
--- |
  ; ModuleID = 'shrink-wrap-limitation.ll'
  source_filename = "shrink-wrap-limitation.ll"
  target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
  target triple = "riscv64"

  define void @li_straightline_b(i32 zeroext %a, i32 zeroext %b) {
    %cmp0 = icmp eq i32 %b, 57
    br i1 %cmp0, label %exit, label %do_call

  do_call:                                          ; preds = %0
    %1 = call i32 @foo()
    br label %next

  next:                                             ; preds = %do_call
    %cmp1 = icmp eq i32 %a, 57
    br i1 %cmp1, label %exit, label %do_call2

  do_call2:                                         ; preds = %next
    %2 = call i32 @foo()
    br label %exit

  exit:                                             ; preds = %do_call2, %next, %0
    ret void
  }

  declare zeroext i32 @foo()
...
---
name:            li_straightline_b
alignment:       4
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
noPhis:          false
isSSA:           true
noVRegs:         false
hasFakeUses:     false
callsEHReturn:   false
callsUnwindInit: false
hasEHContTarget: false
hasEHScopes:     false
hasEHFunclets:   false
isOutlined:      false
debugInstrRef:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gpr, preferred-register: '', flags: [  ] }
  - { id: 1, class: gpr, preferred-register: '', flags: [  ] }
  - { id: 2, class: gpr, preferred-register: '', flags: [  ] }
  - { id: 3, class: gpr, preferred-register: '', flags: [  ] }
  - { id: 4, class: gpr, preferred-register: '', flags: [  ] }
  - { id: 5, class: gpr, preferred-register: '', flags: [  ] }
  - { id: 6, class: gpr, preferred-register: '', flags: [  ] }
liveins:
  - { reg: '$x10', virtual-reg: '%0' }
  - { reg: '$x11', virtual-reg: '%1' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    true
  hasCalls:        true
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  isCalleeSavedInfoValid: false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
entry_values:    []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo:
  varArgsFrameIndex: 0
  varArgsSaveSize: 0
body:             |
  ; COPY-COMBINE-INST-LABEL: name: li_straightline_b
  ; COPY-COMBINE-INST: bb.0 (%ir-block.0):
  ; COPY-COMBINE-INST-NEXT:   successors: %bb.4(0x40000000), %bb.1(0x40000000)
  ; COPY-COMBINE-INST-NEXT:   liveins: $x10, $x11
  ; COPY-COMBINE-INST-NEXT: {{  $}}
  ; COPY-COMBINE-INST-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x11
  ; COPY-COMBINE-INST-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x10
  ; COPY-COMBINE-INST-NEXT:   INLINEASM &"#lw0", 1 /* sideeffect attdialect */, 12 /* clobber */, implicit-def early-clobber $x10, 12 /* clobber */, implicit-def early-clobber $x22
  ; COPY-COMBINE-INST-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY [[COPY1]]
  ; COPY-COMBINE-INST-NEXT:   [[ADDI:%[0-9]+]]:gpr = ADDI $x0, 57
  ; COPY-COMBINE-INST-NEXT:   BEQ [[COPY]], killed [[ADDI]], %bb.4
  ; COPY-COMBINE-INST-NEXT:   PseudoBR %bb.1
  ; COPY-COMBINE-INST-NEXT: {{  $}}
  ; COPY-COMBINE-INST-NEXT: bb.1.do_call:
  ; COPY-COMBINE-INST-NEXT:   successors: %bb.2(0x80000000)
  ; COPY-COMBINE-INST-NEXT: {{  $}}
  ; COPY-COMBINE-INST-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
  ; COPY-COMBINE-INST-NEXT:   PseudoCALL target-flags(riscv-call) @foo, csr_ilp32_lp64, implicit-def dead $x1, implicit-def $x2, implicit-def $x10
  ; COPY-COMBINE-INST-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
  ; COPY-COMBINE-INST-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY $x10
  ; COPY-COMBINE-INST-NEXT: {{  $}}
  ; COPY-COMBINE-INST-NEXT: bb.2.next:
  ; COPY-COMBINE-INST-NEXT:   successors: %bb.4(0x40000000), %bb.3(0x40000000)
  ; COPY-COMBINE-INST-NEXT: {{  $}}
  ; COPY-COMBINE-INST-NEXT:   [[ADDI1:%[0-9]+]]:gpr = ADDI $x0, 57
  ; COPY-COMBINE-INST-NEXT:   BEQ [[COPY2]], killed [[ADDI1]], %bb.4
  ; COPY-COMBINE-INST-NEXT:   PseudoBR %bb.3
  ; COPY-COMBINE-INST-NEXT: {{  $}}
  ; COPY-COMBINE-INST-NEXT: bb.3.do_call2:
  ; COPY-COMBINE-INST-NEXT:   successors: %bb.4(0x80000000)
  ; COPY-COMBINE-INST-NEXT: {{  $}}
  ; COPY-COMBINE-INST-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
  ; COPY-COMBINE-INST-NEXT:   PseudoCALL target-flags(riscv-call) @foo, csr_ilp32_lp64, implicit-def dead $x1, implicit-def $x2, implicit-def $x10
  ; COPY-COMBINE-INST-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
  ; COPY-COMBINE-INST-NEXT:   [[COPY4:%[0-9]+]]:gpr = COPY $x10
  ; COPY-COMBINE-INST-NEXT: {{  $}}
  ; COPY-COMBINE-INST-NEXT: bb.4.exit:
  ; COPY-COMBINE-INST-NEXT:   PseudoRET
  bb.0 (%ir-block.0):
    successors: %bb.4(0x40000000), %bb.1(0x40000000)
    liveins: $x10, $x11

    %1:gpr = COPY $x11
    %0:gpr = COPY $x10
    INLINEASM &"#lw0", 1 /* sideeffect attdialect */, 12 /* clobber */, implicit-def early-clobber $x10, 12 /* clobber */, implicit-def early-clobber $x22
    %2:gpr = COPY %0
    %3:gpr = ADDI $x0, 57
    BEQ %1, killed %3, %bb.4
    PseudoBR %bb.1

  bb.1.do_call:
    successors: %bb.2(0x80000000)

    ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
    PseudoCALL target-flags(riscv-call) @foo, csr_ilp32_lp64, implicit-def dead $x1, implicit-def $x2, implicit-def $x10
    ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
    %4:gpr = COPY $x10

  bb.2.next:
    successors: %bb.4(0x40000000), %bb.3(0x40000000)

    %5:gpr = ADDI $x0, 57
    BEQ %2, killed %5, %bb.4
    PseudoBR %bb.3

  bb.3.do_call2:
    successors: %bb.4(0x80000000)

    ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
    PseudoCALL target-flags(riscv-call) @foo, csr_ilp32_lp64, implicit-def dead $x1, implicit-def $x2, implicit-def $x10
    ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
    %6:gpr = COPY $x10

  bb.4.exit:
    PseudoRET
...
